version: "3"
services: 
  mysql.demis:
    image: mysql:8.0.33
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    volumes: 
      - /home/morwini/projects/demis/data/mysql:/var/lib/mysql
  php.demis:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - 8080:8080
    volumes: 
      - /home/morwini/projects/demis:/app
      